package com.taoqibao.entity;

public class CarMain {
	public String mainId;
	public String ypId;
	public String modelCode;
	public String modelDesc;
	public String yearDesc;
	public String gearboxDesc;
	public int factoryId;
	public String ypFactoryId;
	public String factoryCode;
	public String factoryName;
	public int brandId;
	public String ypBrandId;
	public String brandCode;
	public String brandName;
	public int lineId;
	public String ypLineId;
	public String lineCode;
	public String lineName;
	public String lineDesc;
	public int engineId;
	public String engineDesc;
	public String tqbEngineId;
	public String engineCode;
	public String engineName;
	public String engineModel;
	public String bodyDesc;
	public String dodyName;
	public String doorNum;
	public String seatNum;
	public String marketYear;
	public String stopYear;
	public String yearName;
	public String gearBoxType;
	public String gearBoxNum;
	public String gearBoxModel;
	public String basePlateCode;
	public String countryModelCode;
}
