package com.taoqibao.entity;

import com.taoqibao.widget.sortlistview.SortModel;


public class Customer {
	public String idCar;
	public String idCustomer;
	public String carNo;
	public String name;
	public String sex;
	public String customerSource;
	public String customerType;
	public String companyName;
	public String cellPhone;
	public String birthday;
	public String factoryYear;
	public String vin1_4;
	public String vin5_8;
	public String vin9_12;
	public String vin13_17;
	public String vin;
	public String creationtime;
	public String modifiedtime;
	public String creator;
	public String modifier;
	public String idOwnOrg;
	public String isDel;
	public String carModel;
	public String carPrefix;
	public String showCarNo;
	public String brandId;
	public String factoryId;
	public String lineId;
	public String engineId;
	public String mainId;
	public String showCarName;
	public String contacts;
	public String contactTelephone;
	public String mileage;
	public String mnemonic;
	public String qq;
	public String wechart;
	public String province;
	public String city;
	public String area;
	public String street;
	public String address;
	public String detailAddress;
	public String insuranceCompany;
	public String insurancepolicyNo;
	public String insuranceexpiryDate;
	public String annualDate;
	public String driverExpiryDate;
	public String maritalStatus;
	public String monthlyIncome;
	public String idNumber;
	public String personHobby;
	public String memo;
	public String engineNumber;
	public String factoryCode;
	public String isImportExcel;
	public String idInsuranceCompany;
	public String keyWord;
	public SortModel sortModel;
}
