package com.taoqibao.entity;

public class Stuff {
	public String pkId;
	public String idMdmPart;
	public String nameStandard;
	public String code;
	public String name;
	public String brand;
	public String standard;
	public String spec;
	public String unit;
	public String idPartCategory;
	public String isDelete;
	public String mnemonic;
	public String avgPrice;
	public String supplierCode;
	public String shopPrice;
	public String purchasePrice;
	public String sellPrice;
	public String defaultStore;
	public String oe;
	public String safeStock;
	public String creationTime;
	public String modifiedTime;
	public String creator;
	public String modifier;
	public String idOwnOrg;
	public String categoryName;
	public String col1;
	public String col2;
	public String col3;
	public String col4;
	public String col5;
	public String col6;
	public String col7;
	public String col8;
	public String col9;
	public String col10;
	public String showName;
	public String partNameShow;
	public boolean stockNum;
	public String lastPurchasePrice;
	public String stockNumber;
	public String stockShowName;
}
